services:
    cache_warmer.usecase_cache_warmup:
        class: \vonZnotz\CacheWarmer\UseCase\CacheWarmup
        arguments: ['@cache_warmer.service_cache_warmer', '@cache_warmer.service_sitemap_provider']

    cache_warmer.service_cache_warmer:
        class: \vonZnotz\CacheWarmer\Service\CacheWarmer\CacheWarmerInterface

    cache_warmer.service_sitemap_provider:
        class: \vonZnotz\CacheWarmer\Service\CacheWarmer\SitemapProviderInterface